imagecaptiongen/captions/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed
from wtforms.fields import MultipleFileField
from wtforms import StringField, SubmitField, SelectMultipleField, widgets
from wtforms.validators import DataRequired, Length, ValidationError



class PredictForm(FlaskForm):
    image_pred = MultipleFileField('Select Images', validators=[FileAllowed(['jpg', 'jpeg', 'png'], 'Images only!')])
    url_image = StringField('Image URL')
    model = SelectMultipleField('Models', choices=[('blip', 'BLIP (Recommended)'), ('git', 'GIT ')],
                                option_widget=widgets.CheckboxInput(), widget=widgets.ListWidget(prefix_label=False))
    submit = SubmitField('Predict')

    def validate_model(self, model):
        if not model.data:
            raise ValidationError('At least one model must be selected.')
        valid_models = ['blip', 'git']
        invalid_models = set(model.data) - set(valid_models)
        if invalid_models:
            raise ValidationError(f'Select appropriate model(s). Invalid model(s): {", ".join(invalid_models)}')

    def validate(self):
        if not FlaskForm.validate(self):
            return False
        if not self.image_pred.data and not self.url_image.data:
            msg = 'Either an image or a URL must be provided.'
            self.image_pred.errors.append(msg)
            self.url_image.errors.append(msg)
            return False
        return True

class UpdateCaptionForm(FlaskForm):
    caption = StringField('Caption', validators=[DataRequired(), Length(min=2, max=200)])
    submit = SubmitField('Update Caption')

imagecaptiongen/__init__.py
from math import floor
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from imagecaptiongen.config import Config
from datetime import datetime
import stripe


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    
    from imagecaptiongen.users.routes import users
    from imagecaptiongen.captions.routes import captions
    from imagecaptiongen.main.routes import main
    from imagecaptiongen.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(captions)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    
    # Define the time_since function
    def time_since(dt):
        now = datetime.utcnow()
        diff = now - dt

        periods = (
            (diff.days / 365, "year", "years"),
            (diff.days / 30, "month", "months"),
            (diff.days / 7, "week", "weeks"),
            (diff.days, "day", "days"),
            (diff.seconds / 3600, "hour", "hours"),
            (diff.seconds / 60, "min", "mins"),
            (diff.seconds, "second", "seconds"),
        )

        for period, singular, plural in periods:
            if floor(period) >= 1:
                return "%d %s ago" % (period, singular if floor(period) == 1 else plural)

        return "just now"

    # Register the time_since function as a Jinja filter
    app.jinja_env.filters['time_since'] = time_since

    return app

imagecaptiongen/captions/routes.py
from datetime import datetime, timedelta
import os
import re 
from imagecaptiongen import db 
from flask import (render_template, url_for, flash, jsonify, g,
                   redirect, request, abort, Blueprint, Response, current_app)
from flask_login import current_user, login_required
from imagecaptiongen.models import ImgCap
from imagecaptiongen.captions.forms import PredictForm, UpdateCaptionForm
from imagecaptiongen.captions.utils import (is_valid_url, check_prediction_limit, 
                                            process_images, process_url_image, save_to_table)
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from sqlalchemy import or_, func


captions = Blueprint('captions', __name__)


@captions.before_request
def before_request():
    try:
        if current_user.is_authenticated:
            blip_usr_ratings = ImgCap.query.filter(ImgCap.selected_model=='blip', ImgCap.rating>0).all()
            git_usr_ratings = ImgCap.query.filter(ImgCap.selected_model=='git', ImgCap.rating>0).all()
            blip_usr_avg = sum([r.rating for r in blip_usr_ratings]) / len(blip_usr_ratings) if blip_usr_ratings else 0
            git_usr_avg = sum([r.rating for r in git_usr_ratings]) / len(git_usr_ratings) if git_usr_ratings else 0
            multiple_model_cap_cnt = ImgCap.query.filter(ImgCap.num_models_used==2).count()
            blip_model_sel_cnt = ImgCap.query.filter(ImgCap.num_models_used==2,ImgCap.selected_model=='blip').count()
            git_model_sel_cnt = ImgCap.query.filter(ImgCap.num_models_used==2,ImgCap.selected_model=='git').count()
            blip_score = (blip_model_sel_cnt / (multiple_model_cap_cnt or 1))
            git_score = (git_model_sel_cnt / (multiple_model_cap_cnt or 1))
            max_avg = 6
            g.blip_avg = (blip_usr_avg + blip_score) / max_avg * 5
            g.git_avg = (git_usr_avg + git_score) / max_avg * 5
            scores = {'BLIP': round(10*blip_score),'GIT': round(10*git_score)}
            g.scored_model = max(scores, key=scores.get)
            g.max_score = max(scores.values())
    except Exception as e:
        print(f"An error occurred: {e}")

@captions.route("/caption/<int:img_id>", methods=['GET', 'POST'])
@login_required
def caption(img_id):
    img = ImgCap.query.get_or_404(img_id)
    if not img:
        return 'Img Not Found!', 404 
    image_file = url_for('static', filename='uploads/'+ img.img)
    return image_file


@captions.route("/user_captions")
def user_captions():
    print(f'request.args: {request.args}')
    date_filter = request.args.get('date')
    custom_date_filter = request.args.get('custom_date')

    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        imgs = ImgCap.query.filter_by(user_id=current_user.id)

        if date_filter == 'today':
            date_filter = datetime.today().date()
            print(f"Date filter: {date_filter}")
            imgs = imgs.filter(func.date(ImgCap.date_uploaded) == date_filter)
            print(f"Images: {imgs.all()}")
        elif date_filter == 'last_week':
            one_week_ago = datetime.today().date() - timedelta(days=7)
            imgs = imgs.filter(func.date(ImgCap.date_uploaded) >= one_week_ago)
        elif date_filter == 'custom' and custom_date_filter:
            custom_date_filter = datetime.strptime(custom_date_filter, '%Y-%m-%d').date()
            imgs = imgs.filter(func.date(ImgCap.date_uploaded) == custom_date_filter)

        imgs = imgs.order_by(ImgCap.date_uploaded.desc()).paginate(page=page, per_page=2)
        num_predictions = imgs.total
    else:
        imgs = ImgCap.query.limit(2).all()
        num_predictions = len(imgs)

    return render_template('captions/user_captions.html', title='User Captions', 
                            imgs=imgs, num_predictions=num_predictions)


@captions.route("/search", methods=['GET'])
def search():
    query = request.args.get('q')
    page = request.args.get('page', 1, type=int)
    if current_user.is_authenticated:
        imgs = ImgCap.query.filter(or_(ImgCap.name.contains(query), \
                                       ImgCap.caption.contains(query),\
                                       ImgCap.tag.contains(query)))\
                            .filter_by(user_id=current_user.id)\
                            .order_by(ImgCap.date_uploaded.desc())\
                            .paginate(page=page, per_page=2)
    else:
        imgs = ImgCap.query.filter(or_(ImgCap.name.contains(query), ImgCap.caption.contains(query),\
                                       ImgCap.tag.contains(query))).all()
    return render_template('captions/user_captions.html', title='Searched Captions', imgs=imgs)

@captions.route("/caption/delete/<int:img_id>", methods=['POST'])
@login_required
def delete_caption(img_id):
    image = ImgCap.query.get_or_404(img_id)
    if image.author != current_user:
        abort(403)
    picture_path = os.path.join(current_app.root_path, 'static/uploads', image.img)
    print(picture_path)
    if os.path.exists(picture_path):
        os.remove(picture_path)
    db.session.delete(image)
    db.session.commit()
    flash('Image and caption deleted!', 'danger')
    return redirect(url_for('captions.user_captions'))

@captions.route("/caption/update/<int:img_id>", methods=['GET', 'POST'])
@login_required
def update_caption(img_id):
    image = ImgCap.query.get_or_404(img_id)
    if image.author != current_user:
        abort(403)
    form = UpdateCaptionForm()
    if form.validate_on_submit():  # If the form is submitted and valid
        image.caption = form.caption.data  # Update the image's caption
        image.is_user_modified = True  # Update the is_user_modified flag
        image.date_uploaded = datetime.utcnow()  # Update the date uploaded
        db.session.commit()  # Commit the changes to the database
        flash('Caption updated successfully', 'success')
        return redirect(url_for('captions.user_captions'))
    elif request.method == 'GET':
        form.caption.data = image.caption
    return render_template('captions/update_caption.html', title='Update Caption', form=form, image=image)

@captions.route('/caption/rate/<int:img_id>/<int:rating>', methods=['POST'])
@login_required
def rate_caption(img_id, rating):
    print(f"Rate caption called with img_id: {img_id} and rating: {rating}")  # print statement 1
    img = ImgCap.query.get_or_404(img_id)
    print(f"Image fetched from database: {img}")  # print statement 2
    if img.user_id != current_user.id:
        abort(403)
    img.rating = float(rating)
    db.session.commit()
    print(f"Rating updated and committed: {img.rating}")  # print statement 3
    return jsonify({'status': 'success'})

@captions.route('/caption/update_tag/<int:img_id>', methods=['POST'])
@login_required
def update_tag(img_id):
    img = ImgCap.query.get_or_404(img_id)
    img.tag = request.form['tag']
    db.session.commit()
    return redirect(url_for('captions.user_captions'))


@captions.route("/predict", methods=['GET', 'POST'])
@login_required
def predict():
    form = PredictForm()
    if form.is_submitted():
        if form.validate():
            selected_models = request.form.getlist('model')
            images = request.files.getlist('image_pred')
            url_image = form.url_image.data if hasattr(form, 'url_image') else ''
            print(f'url_image: {url_image}')
            print(f'valid url: {is_valid_url(url_image)}')
            if not current_user.is_premium():
                check_user_limit = check_prediction_limit(current_user, images)
                if not check_user_limit:
                    flash('Free users are limited to 5 predictions.', 'warning')
                    return redirect(url_for('main.home'))
            captions, img_saved = ({}, []) if not images else process_images(images, selected_models, current_app._get_current_object())
            print(f'captions: {captions}, img_saved: {img_saved}')
            if is_valid_url(url_image):
                captions_url, img_saved_url = process_url_image(url_image, selected_models)
                print(f'captions_url: {captions_url}, img_saved_url: {img_saved_url}')
                captions.update(captions_url)
                img_saved.append(img_saved_url)
            print(f'captions: {captions}, img_saved: {img_saved}')
            if len(selected_models) == 2:
                return render_template('captions/select_caption.html',  title='Select Captions', captions=captions, img_saved=img_saved)
            elif len(selected_models) == 1:
                save_to_table(img_saved, captions, selected_models[0],num_models_used=1)
                return redirect(url_for('captions.user_captions')) # Save the captions to the database
        else:
            flash('Check your inputs', 'danger')
    return render_template('captions/predict.html',  title='Predict Captions', form=form)


@captions.route("/select_caption", methods=['POST'])
@login_required
def select_caption():
    print(request.form)
    image_data = {}
    for key in request.form.keys():
        match = re.match(r'(\w+)\[(\w+\.\w+)\]', key)
        if match:
            field, image_filename = match.groups()
            if image_filename not in image_data:
                image_data[image_filename] = {}
            for value in request.form.getlist(key):
                image_data[image_filename][field] = value
    print(f"Image Data - {image_data}")
    save_to_table(image_data, num_models_used=2)
    return redirect(url_for('captions.user_captions'))

@captions.route("/download_captions", methods=['GET'])
@login_required
def download_captions():
    format = request.args.get('format', 'csv')  # Default to 'csv' if no format is specified
    if not current_user.is_premium():

imagecaptiongen/main/routes.py
from flask import render_template, Blueprint
# from flask import request, flash, redirect, url_for, current_app
from flask_login import current_user
from imagecaptiongen import db
from imagecaptiongen.models import User
# import stripe
# from stripe.error import (CardError, RateLimitError, InvalidRequestError, 
#                            AuthenticationError, APIConnectionError, StripeError)

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    if current_user.is_authenticated:
        return render_template('main/user_home.html', title='User Home')
    else:
        return render_template('main/home.html', title='Home')
    
@main.route('/unsubscribe', methods=['POST'])
def unsubscribe():
  # Get the current user
  user = User.query.get(current_user.id)
  # Update the membership_type
  user.membership_type = 'free'
  # Save the changes
  db.session.commit()
  return 'Success'

@main.route('/subscribe', methods=['POST'])
def subscribe():
  # Get the current user
  user = User.query.get(current_user.id)
  # Update the membership_type
  user.membership_type = 'premium'
  # Save the changes
  db.session.commit()
  return 'Success'


# @main.route('/payment/<membership_type>', methods=['GET', 'POST'])
# def payment(membership_type):
#     if request.method == 'POST':
#         try:
#             customer = stripe.Customer.create(
#                 email=request.form['stripeEmail'],
#                 source=request.form['stripeToken']
#             )

#             charge = stripe.Charge.create(
#                 customer=customer.id,
#                 amount=500,
#                 currency='usd',
#                 description='Premium Membership'
#             )

#             subscription = stripe.Subscription.create(
#                 customer=customer.id,
#                 items=[{'plan': 'Image Caption'}],
#             )

#             flash('Your payment has been processed! You are now a premium member!', 'success')
#             return redirect(url_for('users.login'))
        
#         except CardError as e:
#             # Since it's a decline, CardError will be caught
#             body = e.json_body
#             err  = body.get('error', {})
#             flash(f"Status is: {e.http_status}. Type is: {err.get('type')}. Code is: {err.get('code')}. Message is: {err.get('message')}.")
#         except RateLimitError as e:
#             # Too many requests made to the API too quickly
#             flash("Too many requests made to the API too quickly. Please try again later.")
#         except InvalidRequestError as e:
#             # Invalid parameters were supplied to Stripe's API
#             flash("Invalid parameters were supplied to Stripe's API. Please try again.")
#         except AuthenticationError as e:
#             # Authentication with Stripe's API failed
#             flash("Authentication with Stripe's API failed. Please try again.")
#         except APIConnectionError as e:
#             # Network communication with Stripe failed
#             flash("Network communication with Stripe failed. Please try again.")
#         except StripeError as e:
#             # Display a very generic error to the user, and maybe send yourself an email
#             flash("An error occurred while processing your payment. Please try again.")
#         except Exception as e:
#             # Something else happened, completely unrelated to Stripe
#             flash("An error occurred while processing your payment. Please try again.")

#     return render_template('main/payment.html', title='Payment', key=current_app.config['STRIPE_PUBLIC_KEY'])

imagecaptiongen/templates/captions/update_caption.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="d-flex justify-content-center" style="padding-top: 20px;">
                    <img src="{{ url_for('static', filename='uploads/'+ image.img) }}" class="card-img-top caption-img" alt="Image" style="width: 100px; height: 100px;">
                </div>
                <div class="card-body">
                    <h6 class="card-title text-center">Current Caption:</h6>
                    <p class="card-text text-center">{{ image.caption }}</p>
                    <form method="POST" action="{{ url_for('captions.update_caption', img_id=image.id) }}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.caption(class="form-control", placeholder="Enter new caption") }}
                        </div>
                        <div class="text-center">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

imagecaptiongen/templates/captions/user_captions.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <form method="GET" action="{{ url_for('captions.user_captions') }}" class="form-inline d-flex justify-content-between">
            <div class="form-group mb-2">
                <h4 style=" margin-bottom: 1rem; color: rgb(41, 81, 71);"> Total predictions : {{ num_predictions }}</h4>
            </div>
            <div class="form-group mb-2">
                <label for="dateFilter" class="mr-2">Period:</label>
                <select id="dateFilter" name="date" class="form-control mr-2">
                    <option value="today">Today</option>
                    <option value="last_week">Last Week</option>
                    <option value="custom">Custom</option>
                </select>
                <input type="date" id="customDateFilter" name="custom_date" class="form-control mr-2" style="display: none;">
                <button type="submit" class="btn btn-outline-info">Filter</button>
            </div>
        </form>
        {% for img in imgs.items %}
            <div class="card mb-4">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ url_for('static', filename='uploads/'+ img.img)}}" class="card-img m-3 caption-img" alt="Uploaded Image">
                    </div>
                    <div class="col-md-8 p-2">
                        <div class="card-body">
                                <h6 class="card-title">{{ img.caption }}</h6>
                                <p class="card-text"><small class="text-muted">Modified {{ img.date_uploaded|time_since }}</small></p>
                                {% if current_user.is_authenticated %}
                                <div class=" d-flex justify-content-between align-items-start">
                                    <!-- Star Rating -->
                                    <div class="rating" id="rating{{img.id}}">
                                        {% for i in range(5) %}
                                            {% if img.rating is not none and i < img.rating %}
                                                <i class="rating__star fa fa-star" ></i>
                                            {% else %}
                                                <i class="rating__star fa fa-star-o" ></i>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    <div>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#ratingModal{{img.id}}">
                                        <i class="fa fa-pencil fa-xs"></i> <!-- Pencil icon -->
                                    </button>
                                    <!-- Rating Modal -->
                                    <div class="modal fade" id="ratingModal{{img.id}}" tabindex="-1" role="dialog" aria-labelledby="ratingModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    {% if not img.is_user_modified %}
                                                        <h5 class="modal-title" id="captionModalLabel">Modify the Caption</h5>
                                                    {% else %}
                                                        <h5 class="modal-title" id="captionModalLabel">You modified this caption before</h5>
                                                    {% endif %}
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form method="POST" action="{{ url_for('captions.update_caption', img_id=img.id) }}">
                                                    <div class="modal-body">
                                                        {% if not img.is_user_modified %}
                                                            <p>Would you like to modify the caption?</p>
                                                        {% else %}
                                                            <p>Would you like to modify the caption again?</p>
                                                        {% endif %}
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Proceed</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-outline-danger btn-sm ml-2" data-toggle="modal" data-target="#deleteModal{{img.id}}">
                                        <i class="fa fa-trash fa-xs"></i> <!-- Trash icon -->
                                    </button>
                                </div>
                                </div>
                                <!-- Modal -->
                                <div class="modal fade" id="deleteModal{{img.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                Are you sure you want to delete this image?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                    <form method="POST" action="{{ url_for('captions.delete_caption', img_id=img.id) }}">
                                                        <input type="submit" class="btn btn-danger" value="Delete">
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="tag-icon" onclick="showInputField('tagInput{{img.id}}')">
                                    <i class="fa fa-tag"></i> <!-- Tag icon -->
                                </div>
                                {% if img.tag %}
                                    <span id="tagDisplay{{img.id}}" style="font-size: 0.8em;">{{ img.tag }}</span>
                                {% endif %}
                                <form method="POST" action="{{ url_for('captions.update_tag', img_id=img.id) }}" id="tagInput{{img.id}}" style="display: none; width: 100px; height: 30px; padding: 5px;" onsubmit="event.preventDefault(); updateTag(this, 'tagDisplay{{img.id}}');">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Tag" name="tag" value="{{ img.tag if img.tag else '' }}" style="width: 100px; height: 30px; font-size: 0.8em;">
                                    </div>
                                </form>
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center" >
                {% for page_num in imgs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                        {% if imgs.page == page_num %}
                            <li class="page-item active"><a class="page-link" href="{{ url_for('captions.user_captions', page=page_num) }}" style="color: #e7f1f3; background-color: #17a2b8; border: #17a2b8;">{{ page_num }}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="{{ url_for('captions.user_captions', page=page_num) }}" style="color: #17a2b8;">{{ page_num }}</a></li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled"><span class="page-link" style="color: #17a2b8;">...</span></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sugar/2.0.4/sugar.min.js"></script>    
    <script src="{{ url_for('static', filename='rating.js')}}"></script>
    <script>
        document.getElementById('dateFilter').addEventListener('change', function(e) {
            var customDateFilter = document.getElementById('customDateFilter');
            if (e.target.value === 'custom') {
                customDateFilter.style.display = 'block';
            } else {
                customDateFilter.style.display = 'none';
            }
        });
        function showInputField(tagInputId) {
            var tagInput = document.getElementById(tagInputId);
            if (tagInput) {
                tagInput.style.display = 'block';
            }
        }
        function updateTag(form, tagDisplayId) {
            var tag = form.elements['tag'].value;
            $.ajax({
                type: form.method,
                url: form.action,
                data: $(form).serialize(),
                success: function() {
                    document.getElementById(tagDisplayId).textContent = tag;
                    form.style.display = 'none'; // Hide the input field
                    document.getElementById(tagDisplayId).style.display = 'inline'; // Show the tag text
                }
            });
        }
    </script>
{% endblock  %}
{% block sidebar %}
<li class="list-group-item list-group-item-light"><a href="{{ url_for('captions.predict') }}" >Predict More Captions</a></li>
    <div class="container" style="border-radius: 5px;border: 1px solid rgb(222, 221, 221);">
        <p style="margin-top: 1rem;"> {{g.scored_model}} model chosen {{g.max_score}} out of 10 times</p>
        <canvas id="myChart" height="220" style="margin-top: 1.5rem;"></canvas>
        <!-- Include Chart.js -->
        <script>
            var blipAvg = {{ g.blip_avg|tojson|safe if g.blip_avg is not none else 0 }};
            var gitAvg = {{ g.git_avg|tojson|safe if g.git_avg is not none else 0 }};
        </script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <!-- Include chartjs-plugin-datalabels -->
        <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>
        <script src="{{ url_for('static', filename='modelchart.js')}}"></script>
    </div>
{% endblock %}