imagecaptiongen/models/__init__.py
from datetime import datetime
from imagecaptiongen import db, login_manager
from flask_login import UserMixin
from itsdangerous import URLSafeTimedSerializer as Serializer
from flask import current_app


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    membership_type = db.Column(db.String(10), nullable=False, default='free')
    captions = db.relationship('ImgCap', backref='author', lazy=True)

    def get_reset_token(self):
        key = current_app.config['SECRET_KEY']
        print(f'key: {key} ')
        s = Serializer(current_app.config['SECRET_KEY'])
        print(s.dumps({'user_id': self.id}))
        return s.dumps({'user_id': self.id})

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token, max_age=1800)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}', '{self.membership_type}')"
    
    def is_premium(self):
        return self.membership_type == 'premium'


class ImgCap(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    img = db.Column(db.Text, unique=True, nullable=False)  
    name = db.Column(db.Text, nullable=False)
    date_uploaded = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    mimetype = db.Column(db.Text, nullable=False)  
    selected_model = db.Column(db.Text, nullable=False)
    num_models_used = db.Column(db.Integer, nullable=True)
    caption = db.Column(db.Text, nullable=False)
    is_user_modified = db.Column(db.Boolean, default=False)
    rating = db.Column(db.Float, nullable=True, default=0.0)
    tag = db.Column(db.Text, nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
       return f"Img('{self.img}','{self.name}', '{self.mimetype}','{self.date_uploaded}','{self.selected_model}','{self.num_models_used}','{self.caption}','{self.is_user_modified}','{self.rating}', '{self.tag}','{self.user_id}')"


imagecaptiongen/captions/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed
from wtforms.fields import MultipleFileField
from wtforms import StringField, SubmitField, SelectMultipleField, widgets
from wtforms.validators import DataRequired, Length, ValidationError



class PredictForm(FlaskForm):
    image_pred = MultipleFileField('Select Images', validators=[FileAllowed(['jpg', 'jpeg', 'png'], 'Images only!')])
    url_image = StringField('Image URL')
    model = SelectMultipleField('Models', choices=[('blip', 'BLIP (Recommended)'), ('git', 'GIT ')],
                                option_widget=widgets.CheckboxInput(), widget=widgets.ListWidget(prefix_label=False))
    submit = SubmitField('Predict')

    def validate_model(self, model):
        if not model.data:
            raise ValidationError('At least one model must be selected.')
        valid_models = ['blip', 'git']
        invalid_models = set(model.data) - set(valid_models)
        if invalid_models:
            raise ValidationError(f'Select appropriate model(s). Invalid model(s): {", ".join(invalid_models)}')

    def validate(self):
        if not FlaskForm.validate(self):
            return False
        if not self.image_pred.data and not self.url_image.data:
            msg = 'Either an image or a URL must be provided.'
            self.image_pred.errors.append(msg)
            self.url_image.errors.append(msg)
            return False
        return True

class UpdateCaptionForm(FlaskForm):
    caption = StringField('Caption', validators=[DataRequired(), Length(min=2, max=200)])
    submit = SubmitField('Update Caption')

imagecaptiongen/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from imagecaptiongen.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    membership_type = SelectField('Membership Type', choices=[('free', 'Free'), ('premium', 'Premium')],
                                  validators=[DataRequired()])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        if 'membership_type' in kwargs:
            self.membership_type.default = kwargs['membership_type']


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

imagecaptiongen/__init__.py
from math import floor
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from imagecaptiongen.config import Config
from datetime import datetime
import stripe


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    
    from imagecaptiongen.users.routes import users
    from imagecaptiongen.captions.routes import captions
    from imagecaptiongen.main.routes import main
    from imagecaptiongen.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(captions)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    
    # Define the time_since function
    def time_since(dt):
        now = datetime.utcnow()
        diff = now - dt

        periods = (
            (diff.days / 365, "year", "years"),
            (diff.days / 30, "month", "months"),
            (diff.days / 7, "week", "weeks"),
            (diff.days, "day", "days"),
            (diff.seconds / 3600, "hour", "hours"),
            (diff.seconds / 60, "min", "mins"),
            (diff.seconds, "second", "seconds"),
        )

        for period, singular, plural in periods:
            if floor(period) >= 1:
                return "%d %s ago" % (period, singular if floor(period) == 1 else plural)

        return "just now"

    # Register the time_since function as a Jinja filter
    app.jinja_env.filters['time_since'] = time_since

    return app

imagecaptiongen/main/routes.py
from flask import render_template, Blueprint
# from flask import request, flash, redirect, url_for, current_app
from flask_login import current_user
from imagecaptiongen import db
from imagecaptiongen.models import User
# import stripe
# from stripe.error import (CardError, RateLimitError, InvalidRequestError, 
#                            AuthenticationError, APIConnectionError, StripeError)

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    if current_user.is_authenticated:
        return render_template('main/user_home.html', title='User Home')
    else:
        return render_template('main/home.html', title='Home')
    
@main.route('/unsubscribe', methods=['POST'])
def unsubscribe():
  # Get the current user
  user = User.query.get(current_user.id)
  # Update the membership_type
  user.membership_type = 'free'
  # Save the changes
  db.session.commit()
  return 'Success'

@main.route('/subscribe', methods=['POST'])
def subscribe():
  # Get the current user
  user = User.query.get(current_user.id)
  # Update the membership_type
  user.membership_type = 'premium'
  # Save the changes
  db.session.commit()
  return 'Success'


# @main.route('/payment/<membership_type>', methods=['GET', 'POST'])
# def payment(membership_type):
#     if request.method == 'POST':
#         try:
#             customer = stripe.Customer.create(
#                 email=request.form['stripeEmail'],
#                 source=request.form['stripeToken']
#             )

#             charge = stripe.Charge.create(
#                 customer=customer.id,
#                 amount=500,
#                 currency='usd',
#                 description='Premium Membership'
#             )

#             subscription = stripe.Subscription.create(
#                 customer=customer.id,
#                 items=[{'plan': 'Image Caption'}],
#             )

#             flash('Your payment has been processed! You are now a premium member!', 'success')
#             return redirect(url_for('users.login'))
        
#         except CardError as e:
#             # Since it's a decline, CardError will be caught
#             body = e.json_body
#             err  = body.get('error', {})
#             flash(f"Status is: {e.http_status}. Type is: {err.get('type')}. Code is: {err.get('code')}. Message is: {err.get('message')}.")
#         except RateLimitError as e:
#             # Too many requests made to the API too quickly
#             flash("Too many requests made to the API too quickly. Please try again later.")
#         except InvalidRequestError as e:
#             # Invalid parameters were supplied to Stripe's API
#             flash("Invalid parameters were supplied to Stripe's API. Please try again.")
#         except AuthenticationError as e:
#             # Authentication with Stripe's API failed
#             flash("Authentication with Stripe's API failed. Please try again.")
#         except APIConnectionError as e:
#             # Network communication with Stripe failed
#             flash("Network communication with Stripe failed. Please try again.")
#         except StripeError as e:
#             # Display a very generic error to the user, and maybe send yourself an email
#             flash("An error occurred while processing your payment. Please try again.")
#         except Exception as e:
#             # Something else happened, completely unrelated to Stripe
#             flash("An error occurred while processing your payment. Please try again.")

#     return render_template('main/payment.html', title='Payment', key=current_app.config['STRIPE_PUBLIC_KEY'])

imagecaptiongen/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from imagecaptiongen import db, bcrypt
from imagecaptiongen.models import User
from imagecaptiongen.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from imagecaptiongen.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    membership_type = request.args.get('membership_type', 'standard')
    form = RegistrationForm(membership_type=membership_type)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, membership_type=form.membership_type.data)
        db.session.add(user)
        db.session.commit()
        if membership_type == 'premium':
            return redirect(url_for('main.subscribe'))
        else:
            flash('Your account has been created! You are now able to log in', 'success')
            return redirect(url_for('users.login'))
    return render_template('users/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('users/account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        print(f'User = {user}')
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form)

imagecaptiongen/templates/users/account.html
{% extends "layout.html" %}
{% block totalpage %}
<div style="display: flex; justify-content: center; align-items: flex-start; height: 100vh;">
    <div class="content-section" style="width:50%;">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading" style="margin-top: 1.7rem; margin-left: 1rem;">{{ current_user.username }}</h2>
                <p class="text-secondary" style="margin-top: 1rem; margin-left: 1rem;">{{ current_user.email }}</p>
                <div style="display: flex; justify-content: space-between; margin-top: 1rem; margin-left: 1rem;">
                    <p class="text-secondary membershipType" style="margin-right: 1rem; text-transform: capitalize;">Membership Type: {{ current_user.membership_type }}</p>
                    {% if current_user.membership_type == 'free' %}
                        <a href="{{ url_for('main.subscribe') }}" id="subscribeButton" class="btn btn-outline-info">Subscribe</a>
                    {% else %}
                        <a href="{{ url_for('main.unsubscribe') }}" id="unsubscribeButton" class="btn btn-outline-info">Unsubscribe</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        <div class="modal" id="unsubscribeModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Unsubscribe</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to cancel your premium account?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" id="confirmUnsubscribe">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal" id="subscribeModal">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">Subscribe</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                  Are you sure you want to upgrade to a premium account?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-success" id="confirmSubscribe">Yes</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                </div>
              </div>
            </div>
        </div>  
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function() {
        $('#subscribeButton').click(function(e) {
            e.preventDefault();
            $('#subscribeModal').modal('show');
        });
        
        $('#unsubscribeButton').click(function(e) {
            e.preventDefault();
            $('#unsubscribeModal').modal('show');
        });
        
        $('#confirmSubscribe').click(function() {
            $.ajax({
            url: '/subscribe',
            type: 'POST',
            success: function(response) {
                // Update the membership_type displayed on the page
                $('.membershipType').text('Premium');
                // Close the modal
                $('#subscribeModal').modal('hide');
                location.reload();
            }
            });
        });
        
        $('#confirmUnsubscribe').click(function() {
            $.ajax({
            url: '/unsubscribe',
            type: 'POST',
            success: function(response) {
                // Update the membership_type displayed on the page
                $('.membershipType').text('Free');
                // Close the modal
                $('#unsubscribeModal').modal('hide');
                location.reload();
            }
            });
        });
        });
</script>
{% endblock %}
{% block additional_links %}{% endblock %}

imagecaptiongen/templates/users/login.html
{% extends "layout.html" %}
{% block totalpage %}
<div style="display: flex; justify-content: center; align-items: flex-start; height: 100vh;">
    <div class="content-section" style="width:50%;">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group password-wrapper">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <button id="togglePassword" class="toggle-password">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                        </button>
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                        <button id="togglePassword" class="toggle-password">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                        </button>
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
            </small>
        </div>
    </div>
</div>
<script>
    document.getElementById('togglePassword').addEventListener('click', function (e) {
        e.preventDefault(); // Prevent the default action
        const passwordInput = document.querySelector('.password-wrapper .form-control');
        const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordInput.setAttribute('type', type);
        this.classList.toggle('fa-eye-slash'); // toggle the eye slash icon
    });
</script>
{% endblock %}

imagecaptiongen/templates/users/reset_request.html
{% extends "layout.html" %}
{% block totalpage %}
<div style="display: flex; justify-content: center; align-items: flex-start; height: 100vh;">
    <div class="content-section" style="width:50%;">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}