imagecaptiongen/models/ml_models.py
import os
import pickle
from transformers import BlipProcessor, BlipForConditionalGeneration,AutoProcessor, AutoModelForCausalLM

# Blip Model Initialization
blip_processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large")


# Save Blip models as pickle files
with open(os.path.join('ml_models','blip_processor.pkl'), 'wb') as blip_processor_file:
    pickle.dump(blip_processor, blip_processor_file)

with open(os.path.join('ml_models','blip_model.pkl'), 'wb') as blip_model_file:
    pickle.dump(blip_model, blip_model_file)


# Microsoft Git-Base-COCO Model Initialization
git_processor = AutoProcessor.from_pretrained("microsoft/git-base-coco")
git_model = AutoModelForCausalLM.from_pretrained("microsoft/git-base-coco")


# Save Microsoft Git-Base-COCO models as pickle files
with open(os.path.join('ml_models','git_processor.pkl'), 'wb') as git_processor_file:
    pickle.dump(git_processor, git_processor_file)

with open(os.path.join('ml_models','git_model.pkl'), 'wb') as git_model_file:
    pickle.dump(git_model, git_model_file)

imagecaptiongen/__init__.py
from math import floor
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from imagecaptiongen.config import Config
from datetime import datetime
import stripe


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    
    from imagecaptiongen.users.routes import users
    from imagecaptiongen.captions.routes import captions
    from imagecaptiongen.main.routes import main
    from imagecaptiongen.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(captions)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    
    # Define the time_since function
    def time_since(dt):
        now = datetime.utcnow()
        diff = now - dt

        periods = (
            (diff.days / 365, "year", "years"),
            (diff.days / 30, "month", "months"),
            (diff.days / 7, "week", "weeks"),
            (diff.days, "day", "days"),
            (diff.seconds / 3600, "hour", "hours"),
            (diff.seconds / 60, "min", "mins"),
            (diff.seconds, "second", "seconds"),
        )

        for period, singular, plural in periods:
            if floor(period) >= 1:
                return "%d %s ago" % (period, singular if floor(period) == 1 else plural)

        return "just now"

    # Register the time_since function as a Jinja filter
    app.jinja_env.filters['time_since'] = time_since

    return app

imagecaptiongen/captions/routes.py
from datetime import datetime, timedelta
import os
import re 
from imagecaptiongen import db 
from flask import (render_template, url_for, flash, jsonify, g,
                   redirect, request, abort, Blueprint, Response, current_app)
from flask_login import current_user, login_required
from imagecaptiongen.models import ImgCap
from imagecaptiongen.captions.forms import PredictForm, UpdateCaptionForm
from imagecaptiongen.captions.utils import (is_valid_url, check_prediction_limit, 
                                            process_images, process_url_image, save_to_table)
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from sqlalchemy import or_, func


captions = Blueprint('captions', __name__)


@captions.before_request
def before_request():
    try:
        if current_user.is_authenticated:
            blip_usr_ratings = ImgCap.query.filter(ImgCap.selected_model=='blip', ImgCap.rating>0).all()
            git_usr_ratings = ImgCap.query.filter(ImgCap.selected_model=='git', ImgCap.rating>0).all()
            blip_usr_avg = sum([r.rating for r in blip_usr_ratings]) / len(blip_usr_ratings) if blip_usr_ratings else 0
            git_usr_avg = sum([r.rating for r in git_usr_ratings]) / len(git_usr_ratings) if git_usr_ratings else 0
            multiple_model_cap_cnt = ImgCap.query.filter(ImgCap.num_models_used==2).count()
            blip_model_sel_cnt = ImgCap.query.filter(ImgCap.num_models_used==2,ImgCap.selected_model=='blip').count()
            git_model_sel_cnt = ImgCap.query.filter(ImgCap.num_models_used==2,ImgCap.selected_model=='git').count()
            blip_score = (blip_model_sel_cnt / (multiple_model_cap_cnt or 1))
            git_score = (git_model_sel_cnt / (multiple_model_cap_cnt or 1))
            max_avg = 6
            g.blip_avg = (blip_usr_avg + blip_score) / max_avg * 5
            g.git_avg = (git_usr_avg + git_score) / max_avg * 5
            scores = {'BLIP': round(10*blip_score),'GIT': round(10*git_score)}
            g.scored_model = max(scores, key=scores.get)
            g.max_score = max(scores.values())
    except Exception as e:
        print(f"An error occurred: {e}")

@captions.route("/caption/<int:img_id>", methods=['GET', 'POST'])
@login_required
def caption(img_id):
    img = ImgCap.query.get_or_404(img_id)
    if not img:
        return 'Img Not Found!', 404 
    image_file = url_for('static', filename='uploads/'+ img.img)
    return image_file


@captions.route("/user_captions")
def user_captions():
    print(f'request.args: {request.args}')
    date_filter = request.args.get('date')
    custom_date_filter = request.args.get('custom_date')

    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        imgs = ImgCap.query.filter_by(user_id=current_user.id)

        if date_filter == 'today':
            date_filter = datetime.today().date()
            print(f"Date filter: {date_filter}")
            imgs = imgs.filter(func.date(ImgCap.date_uploaded) == date_filter)
            print(f"Images: {imgs.all()}")
        elif date_filter == 'last_week':
            one_week_ago = datetime.today().date() - timedelta(days=7)
            imgs = imgs.filter(func.date(ImgCap.date_uploaded) >= one_week_ago)
        elif date_filter == 'custom' and custom_date_filter:
            custom_date_filter = datetime.strptime(custom_date_filter, '%Y-%m-%d').date()
            imgs = imgs.filter(func.date(ImgCap.date_uploaded) == custom_date_filter)

        imgs = imgs.order_by(ImgCap.date_uploaded.desc()).paginate(page=page, per_page=2)
        num_predictions = imgs.total
    else:
        imgs = ImgCap.query.limit(2).all()
        num_predictions = len(imgs)

    return render_template('captions/user_captions.html', title='User Captions', 
                            imgs=imgs, num_predictions=num_predictions)


@captions.route("/search", methods=['GET'])
def search():
    query = request.args.get('q')
    page = request.args.get('page', 1, type=int)
    if current_user.is_authenticated:
        imgs = ImgCap.query.filter(or_(ImgCap.name.contains(query), \
                                       ImgCap.caption.contains(query),\
                                       ImgCap.tag.contains(query)))\
                            .filter_by(user_id=current_user.id)\
                            .order_by(ImgCap.date_uploaded.desc())\
                            .paginate(page=page, per_page=2)
    else:
        imgs = ImgCap.query.filter(or_(ImgCap.name.contains(query), ImgCap.caption.contains(query),\
                                       ImgCap.tag.contains(query))).all()
    return render_template('captions/user_captions.html', title='Searched Captions', imgs=imgs)

@captions.route("/caption/delete/<int:img_id>", methods=['POST'])
@login_required
def delete_caption(img_id):
    image = ImgCap.query.get_or_404(img_id)
    if image.author != current_user:
        abort(403)
    picture_path = os.path.join(current_app.root_path, 'static/uploads', image.img)
    print(picture_path)
    if os.path.exists(picture_path):
        os.remove(picture_path)
    db.session.delete(image)
    db.session.commit()
    flash('Image and caption deleted!', 'danger')
    return redirect(url_for('captions.user_captions'))

@captions.route("/caption/update/<int:img_id>", methods=['GET', 'POST'])
@login_required
def update_caption(img_id):
    image = ImgCap.query.get_or_404(img_id)
    if image.author != current_user:
        abort(403)
    form = UpdateCaptionForm()
    if form.validate_on_submit():  # If the form is submitted and valid
        image.caption = form.caption.data  # Update the image's caption
        image.is_user_modified = True  # Update the is_user_modified flag
        image.date_uploaded = datetime.utcnow()  # Update the date uploaded
        db.session.commit()  # Commit the changes to the database
        flash('Caption updated successfully', 'success')
        return redirect(url_for('captions.user_captions'))
    elif request.method == 'GET':
        form.caption.data = image.caption
    return render_template('captions/update_caption.html', title='Update Caption', form=form, image=image)

@captions.route('/caption/rate/<int:img_id>/<int:rating>', methods=['POST'])
@login_required
def rate_caption(img_id, rating):
    print(f"Rate caption called with img_id: {img_id} and rating: {rating}")  # print statement 1
    img = ImgCap.query.get_or_404(img_id)
    print(f"Image fetched from database: {img}")  # print statement 2
    if img.user_id != current_user.id:
        abort(403)
    img.rating = float(rating)
    db.session.commit()
    print(f"Rating updated and committed: {img.rating}")  # print statement 3
    return jsonify({'status': 'success'})

@captions.route('/caption/update_tag/<int:img_id>', methods=['POST'])
@login_required
def update_tag(img_id):
    img = ImgCap.query.get_or_404(img_id)
    img.tag = request.form['tag']
    db.session.commit()
    return redirect(url_for('captions.user_captions'))


@captions.route("/predict", methods=['GET', 'POST'])
@login_required
def predict():
    form = PredictForm()
    if form.is_submitted():
        if form.validate():
            selected_models = request.form.getlist('model')
            images = request.files.getlist('image_pred')
            url_image = form.url_image.data if hasattr(form, 'url_image') else ''
            print(f'url_image: {url_image}')
            print(f'valid url: {is_valid_url(url_image)}')
            if not current_user.is_premium():
                check_user_limit = check_prediction_limit(current_user, images)
                if not check_user_limit:
                    flash('Free users are limited to 5 predictions.', 'warning')
                    return redirect(url_for('main.home'))
            captions, img_saved = ({}, []) if not images else process_images(images, selected_models, current_app._get_current_object())
            print(f'captions: {captions}, img_saved: {img_saved}')
            if is_valid_url(url_image):
                captions_url, img_saved_url = process_url_image(url_image, selected_models)
                print(f'captions_url: {captions_url}, img_saved_url: {img_saved_url}')
                captions.update(captions_url)
                img_saved.append(img_saved_url)
            print(f'captions: {captions}, img_saved: {img_saved}')
            if len(selected_models) == 2:
                return render_template('captions/select_caption.html',  title='Select Captions', captions=captions, img_saved=img_saved)
            elif len(selected_models) == 1:
                save_to_table(img_saved, captions, selected_models[0],num_models_used=1)
                return redirect(url_for('captions.user_captions')) # Save the captions to the database
        else:
            flash('Check your inputs', 'danger')
    return render_template('captions/predict.html',  title='Predict Captions', form=form)


@captions.route("/select_caption", methods=['POST'])
@login_required
def select_caption():
    print(request.form)
    image_data = {}
    for key in request.form.keys():
        match = re.match(r'(\w+)\[(\w+\.\w+)\]', key)
        if match:
            field, image_filename = match.groups()
            if image_filename not in image_data:
                image_data[image_filename] = {}
            for value in request.form.getlist(key):
                image_data[image_filename][field] = value
    print(f"Image Data - {image_data}")
    save_to_table(image_data, num_models_used=2)
    return redirect(url_for('captions.user_captions'))

@captions.route("/download_captions", methods=['GET'])
@login_required
def download_captions():
    format = request.args.get('format', 'csv')  # Default to 'csv' if no format is specified
    if not current_user.is_premium():

imagecaptiongen/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from imagecaptiongen import db, bcrypt
from imagecaptiongen.models import User
from imagecaptiongen.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from imagecaptiongen.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    membership_type = request.args.get('membership_type', 'standard')
    form = RegistrationForm(membership_type=membership_type)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, membership_type=form.membership_type.data)
        db.session.add(user)
        db.session.commit()
        if membership_type == 'premium':
            return redirect(url_for('main.subscribe'))
        else:
            flash('Your account has been created! You are now able to log in', 'success')
            return redirect(url_for('users.login'))
    return render_template('users/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('users/account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        print(f'User = {user}')
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form)

imagecaptiongen/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" >

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" >

    {% if title %}
        <title>Image Caption - {{ title }}</title>
    {% else %}
        <title>Image Caption</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">Caption Generator</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('captions.user_captions')}}">Home</a>
                    <a class="nav-item nav-link" style="margin-right: 10rem;" href="{{ url_for('captions.predict') }}">Predict</a>
                    <form action="{{ url_for('captions.search') }}" method="get" class="navbar-nav" style="margin-right: 10rem; width: 20rem;" >
                        <!-- Add a search icon inside the search input -->
                        <input class="form-control border-secondary rounded-pill pr-1 search-input" type="search" placeholder="Search" aria-label="Search" name="q" id="example-search-input2">
                        <div class="input-group-append">
                            <!-- Add the btn-search class to the search button -->
                            <button class="btn btn-group-lg text-dark border-0 rounded-pill btn-search" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" style="margin-right: 10rem;" href="{{ url_for('users.login') }}">Predict</a>
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
        </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      {% block totalpage %}{% endblock %}
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          {% block additional_links %}
            {% if current_user.is_authenticated %}
            <div class="content-section">
              <h4>Additional Links</h4>
              <ul class="list-group">
                  <!-- <li class="list-group-item list-group-item-light"><a href="{{ url_for('captions.predict') }}" >Predict More Captions</a></li> -->
                  <li class="list-group-item list-group-item-light">
                      <div class="dropdown">
                      <a class="dropdown-toggle" href="#" role="button" id="downloadDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Download Captions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="downloadDropdown">
                          <a class="dropdown-item" href="{{ url_for('captions.download_captions', format='csv') }}">Download as CSV</a>
                          <a class="dropdown-item" href="{{ url_for('captions.download_captions', format='pdf') }}">Download as PDF</a>
                      </div>
                      </div>
                  </li>
              </ul>
              {% endif %}
              {% endblock %}
              {% block sidebar %} {% endblock %}
            </div>
        </div>
      </div>
    </main>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>